const itemImages = {
  "100000 Steps": require("../../assets/100000_Steps.png"),
  "Airidah's Inexorable Will": require("../../assets/Airidah's_Inexorable_Will.png"),
  "Ancients' Oath": require("../../assets/Ancients'_Oath.png"),
  "Andariel's Visage": require("../../assets/Andariel's_Visage.png"),
  "Asheara's Khanjar": require("../../assets/Asheara's_Khanjar.png"),
  Azurewrath: require("../../assets/Azurewrath.png"),
  "Battle Trance": require("../../assets/Battle_Trance.png"),
  "Black River": require("../../assets/Black_River.png"),
  "Blood Artisan's Cuirass": require("../../assets/Blood_Artisan's_Cuirass.png"),
  "Bloodless Scream": require("../../assets/Bloodless_Scream.png"),
  Condemnation: require("../../assets/Condemnation.png"),
  "Cowl of the Nameless": require("../../assets/Cowl_of_the_Nameless.png"),
  "Deathless Visage": require("../../assets/Deathless_Visage.png"),
  "Deathspeaker's Pendant": require("../../assets/Deathspeaker's_Pendant.png"),
  Doombringer: require("../../assets/Doombringer.png"),
  Eaglehorn: require("../../assets/Eaglehorn.png"),
  "Esadora's Overflowing Cameo": require("../../assets/Esadora's_Overflowing_Cameo.png"),
  "Esu's Heirloom": require("../../assets/Esu's_Heirloom.png"),
  "Eyes in the Dark": require("../../assets/Eyes_in_the_Dark.png"),
  "Fields of Crimson": require("../../assets/Fields_of_Crimson.png"),
  "Fists of Fate": require("../../assets/Fists_of_Fate.png"),
  Flamescar: require("../../assets/Flamescar.png"),
  Fleshrender: require("../../assets/Fleshrender.png"),
  "Gloves of the Illuminator": require("../../assets/Gloves_of_the_Illuminator.png"),
  "Gohr's Devastating Grips": require("../../assets/Gohr's_Devastating_Grips.png"),
  "Grasp of Shadow": require("../../assets/Grasp_of_Shadow.png"),
  "Greatstaff of the Crone": require("../../assets/Greatstaff_of_the_Crone.png"),
  "Greaves of the Empty Tomb": require("../../assets/Greaves_of_the_Empty_Tomb.png"),
  "Harlequin Crest": require("../../assets/Harlequin_Crest.png"),
  Hellhammer: require("../../assets/Hellhammer.png"),
  "Howl from Below": require("../../assets/Howl_from_Below.png"),
  "Hunter's Zenith": require("../../assets/Hunter's_Zenith.png"),
  "Iceheart Brais": require("../../assets/Iceheart_Brais.png"),
  "Insatiable Fury": require("../../assets/Insatiable_Fury.png"),
  "Mad Wolf's Glee": require("../../assets/Mad_Wolf's_Glee.png"),
  "Mother's Embrace": require("../../assets/Mother's_Embrace.png"),
  Overkill: require("../../assets/Overkill.png"),
  "Penitent Greaves": require("../../assets/Penitent_Greaves.png"),
  "Rage of Harrogath": require("../../assets/Rage_of_Harrogath.png"),
  "Raiment of the Infinite": require("../../assets/Raiment_of_the_Infinite.png"),
  "Ramaladni's Magnum Opus": require("../../assets/Ramaladni's_Magnum_Opus.png"),
  Razorplate: require("../../assets/Razorplate.png"),
  "Ring of Mendeln": require("../../assets/Ring_of_Mendeln.png"),
  "Ring of Red Furor": require("../../assets/Ring_of_Red_Furor.png"),
  "Ring of the Sacrilegious Soul": require("../../assets/Ring_of_the_Sacrilegious_Soul.png"),
  Skyhunter: require("../../assets/Skyhunter.png"),
  "Staff of Endless Rage": require("../../assets/Staff_of_Endless_Rage.png"),
  "Staff of Lam Esen": require("../../assets/Staff_of_Lam_Esen.png"),
  "Tal Rahsa's Iridescent Loop": require("../../assets/Tal_Rahsa's_Iridescent_Loop.png"),
  Temerity: require("../../assets/Temerity.png"),
  "Tempest Roar": require("../../assets/Tempest_Roar.png"),
  "The Butcher's Cleaver": require("../../assets/The_Butcher's_Cleaver.png"),
  "Vasily's Prayer": require("../../assets/Vasily's_Prayer.png"),
  Windforce: require("../../assets/Windforce.png"),
  "Word of Hakan": require("../../assets/Word_of_Hakan.png"),
  "Writhing Band of Trickery": require("../../assets/Writhing_Band_of_Trickery.png"),
  "X'Fal's Corroded Signet": require("../../assets/X'Fal's_Corroded_Signet.png"),

  NotFound: require("../../assets/NotFound.png"),
  // Add other item names and their corresponding image sources
};

export default itemImages;
